spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/maskpass_db
    username: maskpass
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
  transaction:
    default-timeout: 30s

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      org.springframework.web.socket: DEBUG
      org.springframework.messaging: DEBUG

jwt:
  secret: qwbqwuiobhiqebfoizskldnf389y239rfhnoweuh2389h232f3
  valid-time: 1800000 # 30 minutes

server:
  url: http://localhost:8080

cookie:
  valid-time: 1800000
  name: Authorization

---
spring:
  config:
    activate:
      on-profile: prod

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 50
jwt:
  secret: qwbqwuiobhiqebfoizskldnf389y239rfhnoweuh2389h232f3
  valid-time: 1800000 # 30 minutes

server:
  url: http://localhost:8080

cookie:
  valid-time: 1800000
  name: Authorization