name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - uses: actions/checkout@v2
      - name: Create resources folder if not exists
        run: mkdir -p ./src/main/resources
      - name: Create application.yml file
        run: echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
      - uses: actions/upload-artifact@v4
        with:
          name: application.yml
          path: ./src/main/resources/application.yml

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Test with Gradle
        run: ./gradlew clean test

      - name: Build deploy jar
        run: ./gradlew build

      - name: Send file to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./build/libs/*.jar"
          target: deploy

      - name: Deploy remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            sh deploy/deploy.sh

  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Generate AsciiDoc HTML
        run: ./gradlew asciidoctor

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/docs/asciidoc

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
